name: miria-snap # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: 1.0.2+56 # just for humans, typically '1.2+git' or '1.3.2'
summary: Misskey Client App # 79 char long summary
description: |
  Flutterで構築されたモバイル向けMisskeyクライアントアプリ（Linuxビルド）。

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
architectures:
  - amd64
  - arm64

apps:
  miria:
    command: bin/miria
    extensions: [flutter-stable]

parts:
  miria:
    # See 'snapcraft plugins'
    source: https://github.com/shiosyakeyakini-info/miria
    source-type: git
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
    stage-packages:
      - libsecret-1-0
      - libjsoncpp1
  # Integrate custom dialogs in your snap - doc - snapcraft.io
  # https://forum.snapcraft.io/t/integrate-custom-dialogs-in-your-snap/10825
  zenity-integration:
    plugin: nil
    stage-snaps:
      - zenity-integration
