name: miria-snap # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.13+87' # just for humans, typically '1.2+git' or '1.3.2'
summary: Misskey Client for Mobile # 79 char long summary
description: |
  Misskey Client App built with Flutter

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  miria-snap:
    # See 'snapcraft plugins'
    plugin: flutter
    source: https://github.com/shiosyakeyakini-info/miria.git
    flutter-target: lib/main.dart
    build-packages:
      - libsecret-1-dev
      - libmpv-dev
    stage-packages:
      - libsecret-1-0
      - libmpv1


apps:
  miria-snap:
    command: miria
    extentions: [flutter-stable]
