name: miria-snap # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
summary: Misskey Client for Mobile # 79 char long summary
adopt-info: miria-snap
description: |
  Misskey Client App built with Flutter

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  miria-snap:
    # See 'snapcraft plugins'
    plugin: flutter
    source: https://github.com/shiosyakeyakini-info/miria.git
    flutter-target: lib/main.dart
    build-packages:
      - libsecret-1-dev
      - libmpv-dev
    stage-packages:
      - libsecret-1-0
      - libmpv1
    override-pull:
      snapcraft pull
      VERSION=$(cat pubspec.yaml | grep "version[:]" | cut -d " " -f 2)
      snapcraft set-version $VERSION
  zenity:
    plugin: nil
    stage-packages:
      - zenity
    prime:
      - usr/bin/zenity
      - usr/share/zenity/*

apps:
  miria-snap:
    command: miria
    extentions: [flutter-stable]
    plugs:
      - audio-playback
      - password-manager-service

