name: miria-snap # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: 1.0.2+56 # just for humans, typically '1.2+git' or '1.3.2'
summary: Misskey Client App # 79 char long summary
description: |
  Miria is Misskey client application build with Flutter.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  miria:
    command: miria
    extensions: [flutter-stable]

parts:
  zenity-integration:
    plugin: nil
    stage-snaps:
    - zenity-integration
    
  miria:
    # See 'snapcraft plugins'
    source: https://github.com/shiosyakeyakini-info/miria
    source-type: git
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
      - zenity
      - libfontconfig1-dev
    stage-packages:
      - libsecret-1-0
      - libjsoncpp1
      - zenity
      - libfontconfig1

layout:
  # Fix resource relocation problem of zenity part
  /usr/share/zenity:
    symlink: $SNAP/usr/share/zenity