name: miria-snap # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Misskey Client App # 79 char long summary
description: |
  Miria is Misskey client application build with Flutter.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  miria:
    command: miria
    extensions: [flutter-stable]

parts:
  miria:
    # See 'snapcraft plugins'
    source: https://github.com/shiosyakeyakini-info/miria
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
    stage-packages:
      - libsecret-1-0
      - libjsoncpp1
