name: Snapパッケージのビルド
run-name: Building Miria's Snap package
on: [push]
jobs:
  build:
    name: ビルド
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Generate token
        id:  generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key:  ${{ secrets.PRIVATE_KEY }}

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Build snap ${{ github.ref }}
          body: test build ${{ github.ref }}
          draft: true
          prerelease: true
