name: Snapパッケージのビルド
run-name: Building Miria's Snap package
on: [push]
jobs:
  build:
    name: ビルド
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.2+56
          release_name: Build snap 1.0.2+56
          body: test build 1.0.2+56
          bodyFile: ${{ steps.snapcraft.outputs.snap }}
          draft: true
          prerelease: true
