name: Snapパッケージのビルド
run-name: Building Miria's Snap package
on: [workflow_dispatch]
jobs:
  build:
    name: ビルド
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release v1.0.2+56 --draft ${{ steps.snapcraft.outputs.snap }}         

      - name: Upload SnapStore
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: edge
