name: Snapパッケージのビルド
run-name: Building Miria's Snap package
on: [push]
jobs:
  build:
    name: ビルド
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2

      - name: Build Snap
        run: snapcraft build

      - name: Create tag and release note
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v1.0.2+56 --generate-note --draft miria-snap_1.0.2+56-darty_amd64.snap
